[package]
name = "boilerplate_template"
version = "1.0.0"
authors = []

[addresses]
MyVotingSystem = "0xf108800f6a96e0790977ee819c7e8508251861302a1aaab14bbb464e8c726e7a"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }

[dev-dependencies]
